stages:
  - build
  - deploy

image: node:lts-alpine

variables:
  DOCKER_DRIVER: overlay2
  LIBRARY_NG: $(ls projects | head -n 1)

before_script:
  # Ensure that node works correctly
  - npm -v
  - node -v

# For internal build & publish
.repo-configuration: &configure-npm-repo
  # Ensure that node works correctly
  - npm -v
  - node -v
  # Configure internal repo
  - npm config set strict-ssl false
  - npm config set registry $NPM_REGISTRY
  - npm config set ca null
  - npm config set always-auth true
  - npm config set _auth $NPM_TOKEN

  
build:
  stage: build
  variables:
    NPM_REGISTRY: $NPM_PRIVATE_REGISTRY
    NPM_TOKEN: $NPM_PRIVATE_TOKEN
  before_script:
    - *configure-npm-repo
  script:
    - npm i
    - npm i @angular/cli
    - npm run build:lib
  artifacts:
    expire_in: 1 hour
    paths:
        - dist
    
deploy-internal:
  stage: deploy
  variables:
    NPM_REGISTRY: $NPM_PRIVATE_REGISTRY_3KLES
    NPM_TOKEN: $NPM_PRIVATE_TOKEN
  before_script:
    - *configure-npm-repo
  except:
    - /^.*-dev$/
  script:
    - npm run publish:lib

deploy-public:
  stage: deploy
  variables:
    NPM_TOKEN: $NPM_PUBLIC_TOKEN
  before_script:
    - npm config set always-auth true
    - npm config set _auth $NPM_TOKEN
  only:
    - tags
  script:
    - npm run publish:lib

