stages:
  - build
  - deploy

image: node:lts-alpine

variables:
  DOCKER_DRIVER: overlay2
  LIBRARY_NG: $(ls projects | head -n 1)
  
before_script:
  # Ensure that node works correctly
  - npm -v
  - node -v
  
build:
  stage: build
  script:
    # Install @angular/cli globally
    - npm i
    - npm i @angular/cli
    - npm run build:lib
  artifacts:
    expire_in: 1 hour
    paths:
        - dist
    
deploy-internal:
  stage: deploy
  except:
    - /^.*-dev$/
  script:
    - npm run publish:lib

deploy-public:
  stage: deploy
  only:
    - tags
  before_script:
    - npm config set strict-ssl false
    - npm config set registry $NPM_INTERNAL_REGISTRY
    - npm config set ca null
    - npm config set always-auth true
    - npm config set _auth $NPM_INTERNAL_TOKEN
  script:
    - npm run publish:lib

