export enum EnumType {
    input = 'input',
    select = 'select',
    text = 'text',
    file = 'file',
    imageUpload = 'imageUpload',
    button = 'button',
    checkbox = 'checkbox',
    number = 'number',
    time = 'time',
    date = 'date',
    color = 'color',
    list = 'list',
    multi = 'multi',
    array = 'array',
    group = 'group',
    lineBreak = 'lineBreak',
    badge = 'badge',
    range = 'range',
    currency = 'currency',
    status = 'status',
}
